### ISSUE TITLE
RSpec - OpenSSL::SSL::SSLError

### ISSUE THREAD

**Issue by coorasse** [DynamoMTL/spree_chimpy#50]
When running RSpec tests they ends with the following error:

    OpenSSL::SSL::SSLError: hostname "api.mailchimp.com" does not match the server certificate

Saw also here: https://github.com/neighborly/neighborly/issues/36

**Comment by braidn** [comment]
@coorasse are you still seeing these? And if so what branch?

**Comment by coorasse** [comment]
I'm sorry but four months have passed. I do not remember about that issue. If I face it again I'll reopen the ticket.
