### ISSUE TITLE
Add support for Sidekiq

### ISSUE THREAD

**Issue by bryanmtl** [DynamoMTL/spree_chimpy#54]
@braidn - Chimpy ships with support for [Delayed Job](https://github.com/DynamoMTL/spree_chimpy/blob/master/lib/spree_chimpy.rb#L93-L97) and I'd like to add support for our stores that are using Sidekiq. 

Could you have a look at this for me?

**Comment by braidn** [comment]
Sure thing! Do you want to open this up to anything else? Resque or Beanstalk?

**Comment by bryanmtl** [comment]
Sidekiq is fine for now.

**Comment by johanb** [comment]
I made an attempt at this before: https://github.com/DynamoMTL/spree_chimpy/pull/18 never finished it though.

**Comment by braidn** [comment]
@johanb thank you! I will try and spruce it up/mess with things and see where I get.

**Comment by braidn** [comment]
Ok all, Sidekiq support added to the MailChimp 2.0 branch. Testing internally then will move to master.

**Comment by joshnuss** [comment]
Good stuff @braidn 

At some point in the future we should switch to active_jobs:
http://edgeguides.rubyonrails.org/active_job_basics.html

**Comment by braidn** [comment]
Now? Ha I like the active_jobs api a lot and think that it was a great idea

**Comment by bryanmtl** [comment]
It requires Rails 4.2, I believe. We'll have to wait until we've moved our sites to Spree 3.0

**Comment by DanielWright** [comment]
RIP state_machine

**Comment by javereec** [comment]
I'm encountering an issue when using Sidekiq that the payload is a plain hash where all the Symbols are cast to Strings. I've created a pull request to remedy this, look at https://github.com/DynamoMTL/spree_chimpy/pull/55

**Comment by braidn** [comment]
Closing this out all. Fixed up on master.
