### ISSUE TITLE
Add ability to provide merge vars when subscribing through Spree::Chimpy::SubscribersController

### ISSUE THREAD

**Issue by frahugo** [DynamoMTL/spree_chimpy#58]
This would be handy when we have a merge variable such as "origin" so we can track some people subscribed through the footer on the site.

**Comment by pmichna** [comment]
:+1 I don't use any `User` class in my spree store and now I don't have any possibility to add merge vars.

**Comment by braidn** [comment]
@frahugo I am going to close this due to age. However, I would love to keep the gem scoped to collection of Order Data, and not subscriptions. I am pondering about removing the subscription partial code all together.
