### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by ManuelFrigerio** [DynamoMTL/spree_chimpy#61]
Hi there,

This might be a very silly question and I apologise for that.

I installed the gem and everything is working fine, but I don't understand what is supposed to happen.

I complete one order and then I go back to my MailChimp to see if the user has been added to the list set in the preferences, but it doesn't happen.

Am I doing something wrong?

Thanks
https://guides.github.com/features/mastering-markdown/

**Comment by braidn** [comment]
@ManuelFrigerio are you using any kind of Queueing system like DJ or Sidekiq? Are these working in your development environment?

**Comment by ManuelFrigerio** [comment]
hey @braidn nope, I'm not using any of those. It's not even working on development environment...

**Comment by braidn** [comment]
@ManuelFrigerio can you link a Gist of your spree_chimpy config file for me? You can remove the API and list_id but replace them with some dummy text. Also what version of Spree are you using?

**Comment by ManuelFrigerio** [comment]
Sure, here you go => https://gist.github.com/ManuelFrigerio/6a5739734a13962abef6

Spre version: 2.3-stable

**Comment by joshnuss** [comment]
@ManuelFrigerio Does the list named "TEST" exist in your MC account?

**Comment by ManuelFrigerio** [comment]
Yes

**Comment by joshnuss** [comment]
Can you do a `rails console` and check the value of `Spree::Chimpy.configured?`, it should return `true`

**Comment by joshnuss** [comment]
Also, is user data synced and just not orders? or are both not going thru?

If your email address is not in your "TEST" list, mailchimp wont save the order data.

**Comment by braidn** [comment]
I am not sure that is a valid API key(XXX-us3) to begin with. Also, I highly recommend you use the list_id over the list name. The ID can be found in the settings of each list.

**Comment by ManuelFrigerio** [comment]
@braidn of course that is not a valid API key... I was hiding the real one ;)
As per the list name, the doc says to use the list name and not the list ID.

**Comment by braidn** [comment]
Sweet, yeah my bad. Will get that fixed on the Docs today. Yeah use list_id. Example list_id:

```
config.list_id = ENV['MAILCHIMP_LIST_ID']
```

**Comment by braidn** [comment]
Also @ManuelFrigerio what's the result of Josh's above question concerning Spree::Chimpy.configured? in the Rails console?

**Comment by ManuelFrigerio** [comment]
@braidn

Sweet.
Haven't tested it in the console, will do in a bit!

**Comment by ManuelFrigerio** [comment]
@joshnuss @braidn 

It does say "true"

**Comment by joshnuss** [comment]
And when you create an order, is `order.email` subscribed in your "TEST" list?

**Comment by ManuelFrigerio** [comment]
Sorry @johanb, I don't get you..

**Comment by braidn** [comment]
@ManuelFrigerio I think you might have meant Josh. He is asking that when you complete an order locally, you see the email you used in the order in your TEST list on MailChimp?

**Comment by ManuelFrigerio** [comment]
@braidn Ops, sorry :)

No it doesn't, and that's exactly the issue.
Don't understand if it has something to do with the list_name or something else..

**Comment by braidn** [comment]
Hmm, So weird. Like you did before with the Gist, do you mind adding your Gemfile here? Just to see if there is anything glaring.

**Comment by joshnuss** [comment]
@ManuelFrigerio When we send order data to MailChimp, they only accept data when the email is already subscribed to a list.

You need to make sure you are first subscribed to the list, before you can submit order data against that email account.

**Comment by ManuelFrigerio** [comment]
@joshnuss This wasn't clear at all! ;)

**Comment by braidn** [comment]
@ManuelFrigerio does this mean you have tested it with an existing user to the list and a test order from Spree? Everything working?
