### ISSUE TITLE
Unable to run merge_vars:sync rake task

### ISSUE THREAD

**Issue by Ionut-Milas** [DynamoMTL/spree_chimpy#65]
**When running the rake task : **
       _rake spree_chimpy:merge_vars:sync_
**the following error is raised:**
/home/andreea/.rvm/gems/ruby-2.1.4/bundler/gems/mailchimp-bac6563673e8/lib/spree_chimpy.rb:25:in `configured?': Use RbConfig instead of obsolete and deprecated Config.
/home/andreea/.rvm/gems/ruby-2.1.4/bundler/gems/mailchimp-bac6563673e8/lib/spree_chimpy.rb:25:in`configured?': Use RbConfig instead of obsolete and deprecated Config.
rake aborted!
NoMethodError: undefined method `key' for RbConfig:Module
/home/andreea/.rvm/gems/ruby-2.1.4/bundler/gems/mailchimp-bac6563673e8/lib/spree_chimpy.rb:25:in`configured?'
/home/andreea/.rvm/gems/ruby-2.1.4/bundler/gems/mailchimp-bac6563673e8/lib/spree_chimpy.rb:41:in `list'
/home/andreea/.rvm/gems/ruby-2.1.4/bundler/gems/mailchimp-bac6563673e8/lib/spree_chimpy.rb:61:in`sync_merge_vars'
/home/andreea/.rvm/gems/ruby-2.1.4/bundler/gems/mailchimp-bac6563673e8/lib/tasks/spree_chimpy.rake:5:in `block (3 levels) in <top (required)>'
/home/andreea/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in`eval'
/home/andreea/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spree_chimpy:merge_vars:sync

**This is the spree_chimpy.rb initializer:**

Spree::Chimpy.config do |config|
  # your API key as provided by MailChimp
   config.key = 'api-key'

  # extra api options for the Mailchimp gem
  # config.api_options = { throws_exceptions: false, timeout: 3600 }

  # name of your list, defaults to "Members"
   config.list_name = 'Clienti'

  # define a list of merge vars:
  # - key: a unique name that mail chimp uses. 10 letters max
  # - value: the name of any method on the user class.
  # make sure to avoid any of these reserved field names:
  # http://kb.mailchimp.com/article/i-got-a-message-saying-that-my-list-field-name-is-reserved-and-cant-be-used
  # default is {'EMAIL' => :email}
  config.merge_vars = {
    'EMAIL' => :email,
    'FIRSTNAME' => :first_name,
    'LASTNAME' => :last_name
  }
end

*\* Spree-Chimpy version: 3-stable  **
Could you provide some details on what might be missing?

**Comment by artempankov** [comment]
same issue, any updates?

**Comment by Ionut-Milas** [comment]
No updates ... :(

**Comment by braidn** [comment]
Hey all! Sorry I missed this. @artempankov and @Ionut-Milas do you all mind running this with list_id and the list id over the list name? Sorry again for missing the issue.

**Comment by Ionut-Milas** [comment]
@braidn can't really follow ... 
I should put the list_id as well ?

**Comment by braidn** [comment]
@Ionut-Milas the list name is really a vestige of the older way we were looking up people's lists. Can you remove the list name entirely and add the list_id?

**Comment by Ionut-Milas** [comment]
I tried with the List id .. but no luck ...

**Comment by braidn** [comment]
@Ionut-Milas Will look into it. Thanks!

**Comment by braidn** [comment]
@Ionut-Milas what version of spree are you using? Assuming 3.x but just checking.

**Comment by GraphicDesk** [comment]
Yep 3.0

**Comment by GraphicDesk** [comment]
Also the website is on https don't know if it changes anything....

**Comment by braidn** [comment]
It does not. Have not forgotten about this all. Hopefull get to it soon.

**Comment by joshnuss** [comment]
I remember seeing this before, try `bundle exec rake ...`, that might fix it

**Comment by braidn** [comment]
@GraphicDesk did running `bundle exec` here help out the situation? Still having a lot of issues trying to recreate the issue originally described.

**Comment by GraphicDesk** [comment]
RAILS_ENV=production bundle exec rake spree_chimpy:merge_vars:sync
rake aborted!
NameError: uninitialized constant Spree::Chimpy::Config
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mailchimp-bac6563673e8/lib/spree_chimpy.rb:25:in `configured?'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mailchimp-bac6563673e8/lib/spree_chimpy.rb:41:in `list'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mailchimp-bac6563673e8/lib/spree_chimpy.rb:61:in `sync_merge_vars'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mailchimp-bac6563673e8/lib/tasks/spree_chimpy.rake:5:in `block (3 levels) in <top (required)>'
Tasks: TOP => spree_chimpy:merge_vars:sync
(See full trace by running task with --trace)

**Comment by GraphicDesk** [comment]
I am on Centos... don't know if that affects ...

**Comment by GraphicDesk** [comment]
seems to be working now....

**Comment by samar-mishra** [comment]
bundle exec rake spree_chimpy:merge_vars:sync
/Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bundler/gems/spree_chimpy-af8a138e4678/lib/spree_chimpy.rb:25:in `configured?': Use RbConfig instead of obsolete and deprecated Config.
/Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bundler/gems/spree_chimpy-af8a138e4678/lib/spree_chimpy.rb:25:in `configured?': Use RbConfig instead of obsolete and deprecated Config.
rake aborted!
NoMethodError: undefined method `key' for RbConfig:Module
/Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bundler/gems/spree_chimpy-af8a138e4678/lib/spree_chimpy.rb:25:in `configured?'
/Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bundler/gems/spree_chimpy-af8a138e4678/lib/spree_chimpy.rb:41:in `list'
/Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bundler/gems/spree_chimpy-af8a138e4678/lib/spree_chimpy.rb:61:in `sync_merge_vars'
/Users/Topform/.rvm/gems/ruby-2.1.4@skinnymint/bundler/gems/spree_chimpy-af8a138e4678/lib/tasks/spree_chimpy.rake:5:in `block (3 levels) in <top (required)>'
Tasks: TOP => spree_chimpy:merge_vars:sync
(See full trace by running task with --trace)

**Comment by braidn** [comment]
Will look into it for yah!

**Comment by MOOn2k** [comment]
Same error for me.

**Comment by braidn** [comment]
Will try and check this out for you all. Ultimately we need to go to the new Mailchimp API. @MOOn2k and @samar-mishra are you using Spree 3.0 and above or?

**Comment by MOOn2k** [comment]
v2.3.10

**Comment by braidn** [comment]
Hey @MOOn2k and @samar-mishra what ruby manager are you using? Also are you using the path flag with bundler when installing or are you installing globally?

**Comment by braidn** [comment]
@MOOn2k and @samar-mishra if this is still an issue would it be ok to start a new, fresh issue? Thanks for being awesome.
