### ISSUE TITLE
Spree Chimpy and SSL

### ISSUE THREAD

**Issue by GraphicDesk** [DynamoMTL/spree_chimpy#66]
Any special request regarding working under SSL?

**Comment by braidn** [comment]
@GraphicDesk this should just work. You are talking about your store running under SSL (which it should be)?

**Comment by GraphicDesk** [comment]
Yeah all under https
Pe 09.01.2016 19:31, Braden Douglass <notifications@github.com> a scris:@GraphicDesk this should just work. You are talking about your store running under SSL (which it should be)?

**Comment by braidn** [comment]
@GraphicDesk since this should just work while your site is running under SSL, I am going to close the issue. If you have some more questions or you are having an SSL based error feel free to reopen and I will do my best to figure out what's going on. Thank you.
