### ISSUE TITLE
Two lists in one store

### ISSUE THREAD

**Issue by pmichna** [DynamoMTL/spree_chimpy#72]
I have two subscribers lists: each for a different language. Is there any way to configure `spree_chimpy` to be able to choose dynamically which list to use?  In `Spree::Chimpy.config` I can set only one `list_name`.

**Comment by braidn** [comment]
@pmichna you want to push orders to different lists? What's the use case here?

**Comment by braidn** [comment]
@pmichna I am going to close this due to the age. If it's still an active issue can you create a new issue and we can talk about it? Thank you.
