### ISSUE TITLE
Support for Mailchimp API 3.0

### ISSUE THREAD

**Issue by jkelleyj** [DynamoMTL/spree_chimpy#75]
Mailchimp is retiring their older APIs pretty soon (Dec 2016)
 http://us12.campaign-archive1.com/?u=165abe0a1aa09263bc6ad1397&id=7146f7c68e

Is there anyone working on updating this gem to support 3.0?  It doesn't look like mailchimp has put out a wrapper yet.  They say they are planning to release a wrapper, but I can't find a timeline on that to upgrade what spree_chimpy uses today from 2.0 to 3.0.
http://devs.mailchimp.com/blog/a-good-api-shouldnt-need-an-sdk/

We could move to gibbon instead, as it has 3.0 support now, or we could just directly connect using something like HTTParty.  

@braidn do you have a strong opinion on this? I'm happy to put together a pull request.  I'd probably go with making it configurable for now w/ a default API Version of 2.0 to provide backward compatibility.

**Comment by braidn** [comment]
@jkelleyj thanks for reaching out about this. I actually didn't realize that Mailchimp was retiring V2 so quickly. We should have gone to Gibbon a long time ago. Overall it's always been a (seemingly) better layer on top of their API. It would be amazing if you took a stab at the upgrade. No worries on the backwards compatibility with the API but, it would be amazing if we could keep the gem API layer the same.

**Comment by jkelleyj** [comment]
@braidn I'm picking this up now to integrate Gibbon and setup for V3 API.  There are a few tests not passing out of the gate.  Three due to an expired API Key that I should be able to fix and two related to the resubscribe functionality.  I'm building the feature branch off of master so it can be pulled into the stable versions.  Am I doing something wrong, or are those resub specs outdated?

**Comment by braidn** [comment]
Thanks @jkelleyj ! Throw any legit Mailchimp key in there and it should work. The reuse specs are likely outdated, let's branch from spree 2.4. We then can make this master, deprecate support for lower versions and go from there. Thanks again!

**Comment by jkelleyj** [comment]
Sounds good.  I'll branch from 2-stable and submit the PR against that when
finished.  I'll let you work the branch wizardry to true up the master
branch and 3-stable from there if that's OK.

**Comment by braidn** [comment]
Absolutely 👍

**Comment by jkelleyj** [comment]
Quick question - The specs are pretty heavily stubbed in the interfaces.
Any objection to me adding VCR to record the actual requests and test
response codes?

That would give us a bit better test coverage of the proper usage of Gibbon
as things are changed going forward.

**Comment by jkelleyj** [comment]
resolving this issue via #76

**Comment by jkelleyj** [comment]
Closed via #76
