### ISSUE TITLE
Sending email on completed order

### ISSUE THREAD

**Issue by Irru-** [DynamoMTL/spree_chimpy#81]
Hey there, I've recently deployed a website, and I was interested in sending mails through mailchimp when a customer places an order.

I've added the API key and the list ID, and I can indeed see the 'ecomm/order-add' call being made on the mailchimp account.

My question is, how/where can I configure to send a mail from that point? Do people really need to be added the specific list first?

If so, is that done automatically? It would make little to no sense if a customer would have to subscribe to a list to get an order confirmation email.

**Comment by braidn** [comment]
This gem doesn't handle transaction based email/mailers. It only records the order data for the user against a user in Mailchimp for segmenting.

**Comment by Irru-** [comment]
I appreciate the fast response.

Do you know of any methods to integrate it any other way then? I've also been looking at Mandrill as they are more suited for transaction based emails I believe.

**Comment by braidn** [comment]
Sure! Check out the [Mandrill Mailer](https://github.com/renz45/mandrill_mailer). It's super easy to send Mandrill just a bunch of merge vars and assign a template from Mandrill during specific times in your app where you would use a mailer. Mandrill Mailer's readme should be able to get you going very quickly.

**Comment by Irru-** [comment]
That indeed looks very thorough!

Thanks for the help, even though the problem wasn't related to mailchimp/this gem :)
